version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=latest
      - echo "ECR login complete!"
      
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build --file Dockerfile --tag $REPOSITORY_URI:$IMAGE_TAG --build-arg BUILD_ENV=production .
      - echo "Docker image build complete!"
      
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image pushed successfully!"


